### ISSUE TITLE
Increase targetSdk

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/ShareToInputStick#10]
Just got an email from Google, I forgot about this app:

>Starting Nov 1, 2022, apps that don't target an API level within 2 years of the latest Android release (API 29 and below) won't be available to new users with devices running Android versions newer than your app's target API level. This means that new users won't be able to discover or install your app on Google Play.
>
>Actions:
>
>    We recommend you target Android API 31 or above so that your app continues to reach all Google Play users. For technical guidance, refer to this [migration guide](https://developer.android.com/google/play/requirements/target-sdk).
>    If you don't plan to migrate the app, you don't need to do anything. However, new users will not be able to discover or install your app.
>    To learn more, and to request a 6-month deadline extension, select View details below.

**Comment by krageon** [comment]
Do you estimate it will be complex to upgrade? I could look at it, but because I am not super well versed in android things idk how irritating an upgrade would be.

**Comment by TheLastProject** [comment]
With some luck it's just increasing the number in

https://github.com/TheLastProject/ShareToInputStick/blob/b1c15e349cae9ee3084ab0339e94d209f3467332/app/build.gradle#L15

And some testing to make sure everything works.

I just haven't gotten to it yet :)

**Comment by krageon** [comment]
I think I've got that in me. Wrestling with android studio comes next. Thanks :)

**Comment by TheLastProject** [comment]
Should be fixed in ce0560f20a07e6dfffb62cc2906d36f2be691fce, was more complex than expected because half of everything was deprecated again.

**Comment by krageon** [comment]
You're awesome, thank you :)
