### ISSUE TITLE
URL in metadata broken.

### ISSUE THREAD

**Issue by PanderMusubi** [TheLastProject/ShareToInputStick#28]
URL to repo contains a period and results in 404. Period needs a space before it. See screenshot.

![Screenshot_20240720-193546_F-Droid_1](https://github.com/user-attachments/assets/c6ac7d0f-576e-41b5-86c2-1f02aa67835d)

**Comment by TheLastProject** [comment]
I really don't like adding a space before the dot because it's not correct English to have a space before the end-of-sentence dot. So I rephrased it instead. Fixed in 64061e8adc3f1d43ab90b3e2cc0193cefc8be20f, thanks for notifying me.
