### ISSUE TITLE
Won't directly connect

### ISSUE THREAD

**Issue by Norgus** [TheLastProject/ShareToInputStick#40]
I tried the app with a new inputstick, and when I choose it in the list of detected devices, fails with the message 
```
BT 4.0 RXTX not found
```
I am using BT LTE and have set the encryption password up using the InputStickUtility

edit: forgot to mention that the 'USE INPUTSTICKUTILITY' button does work, but it is very annoying to have to press it every time.

**Comment by TheLastProject** [comment]
While I don't recognize the message you saying "new inputstick" and seeing we're one commit behind on the official library, missing this commit: https://github.com/inputstick/InputStickAPI-Android/commit/6f2056be0f091b900e621c0222452a908f0fc9e7

That sounds believable as reason why you'd have issues (mine is quite old). I'll try to get you a debug build later

**Comment by TheLastProject** [comment]
I created https://github.com/TheLastProject/ShareToInputStick/pull/42, it contains a debug build. Could you see if that works for you? You may have to uninstall the app first before this wants to install.

**Comment by Norgus** [comment]
> I created https://github.com/TheLastProject/ShareToInputStick/pull/42, it contains a debug build. Could you see if that works for you? You may have to uninstall the app first before this wants to install.

Thanks! It worked right away, I have successfully sent text through the bt connection now.
Is it sensible to continue using this build until you update f-droid/play store?

**Comment by TheLastProject** [comment]
Thanks for testing! Yeah, the build is safe, it's just a debug build so it doesn't contain all performance optimizations that are normally applied.

I'll try to cut a new release with this fix soon :)
