### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [TheLastProject/ShareToInputStick#9]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 08 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on Share To InputStick (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve Share To InputStick's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by TheLastProject** [comment]
Oh it's you again, hi :)

In this projects' case I am pretty sure I do literally nothing crypto-related myself, so it would make much more sense to report your findings to the libraries you found them in so they can actually be resolved.
